### ISSUE TITLE
Dictionary Source

### ISSUE THREAD

**Issue by murasu** [NaagAlgates/vasitionary#2]
Hi, Nice app and thanks releasing it under MIT license. We'd like to use the dictionary data in another app of ours. Could you please confirm if this data is covered under the same license? We'll be happy to credit you or any other source where the data comes from. Just want to be clear that we are free to use it for our purpose - both commercial and non-commercial.

**Comment by NaagAlgates** [comment]
Yes, you can use the data and happy to receive credits for it.

**Comment by murasu** [comment]
Thank you. I did some more searches and realised that the dictionary data is from the TVU Tamil Dictionary. I've written to them for permission :)

**Comment by NaagAlgates** [comment]
oh really? Then I should credit them. Cool. Thanks for the heads-up.

**Comment by murasu** [comment]
I think you should also write to them for permission. The material is theirs and I don't think they have made it open. I saw another repo where the developer has (correctly) included a disclaimer that the data is from TVA. you may want to do that too :)

**Comment by NaagAlgates** [comment]
Thank you @murasu , I've done my part!

**Comment by murasu** [comment]
Great! All the best!

**Comment by echeran** [comment]
Hi @NaagAlgates and @murasu,
Sorry for the late reply.  Yes, I noticed as well last year that the data comes from TVA.  That's why I couldn't touch the data, sorry for not getting back to you @NaagAlgates about that.  Instead, I spent more time to finish up my project to semi-automate the creation of a POS-tagged dataset from scratch using and creating data under a permissive license.  I just finished that a few weeks ago, right before the lockdowns etc. went global.

The code is available in [my fork of the repo](https://github.com/echeran/unilex), which is independent of the fact that I am still waiting on approval for a [PR to merge it upstream](https://github.com/unicode-org/unilex/pull/9).  The input data that I am using, the code that I wrote, and the output I created are all under the Unicode license, which is effectively MIT (more specifically, MIT X), with a few minor mods.  You can find more info on the license, motivation, and the code design in the [code's Readme file](https://github.com/echeran/unilex/tree/master/data/stems/ta/dict-data-builder).  I think it should be fine to start using the data there, let me know if you want the data in a different format, like JSON, XML, etc.

-- Elango
